import type { ImageSourcePropType } from 'react-native';

export type BridgeAmbienceProfile = 'none' | 'deep-space' | 'pelagic-megacity' | 'emberline-shipyard' | 'nacre-ice-giant' | 'eventide-eclipse' | 'glass-desert' | 'pilgrim-beacons' | 'aurora-reef' | 'comet-caravan' | 'blue-meridian' | 'vesper-horizon' | 'blueworld-patrol' | 'dawnward-escort' | 'emberfall-frontier' | 'leviathan-orbit' | 'nebula-clouds' | 'asteroid-belt' | 'cinder-comet-shoals' | 'copperline-orbital-foundry';
export type BridgeVistaSource = ImageSourcePropType | { type: 'video'; asset: number };
export type BridgeVistaScene = {
  id: string;
  name: string;
  source: BridgeVistaSource;
  ambience?: BridgeAmbienceProfile;
  /** Opt-in pairing for future Picture Event rewards. Existing vistas stay public. */
  pictureEventUnlock?: boolean;
};

// Built-in vista art is a clean exterior plate. The ship interior and window
// mask stay in App.tsx; gentle motion is composed by BridgeVistaRenderer.
export const BUILT_IN_BRIDGE_VISTAS: BridgeVistaScene[] = [
  { id: 'cinder-comet-shoals', name: 'Cinder Comet Shoals', source: require('./assets/bridge-vistas/cinder-comet-shoals.png'), ambience: 'cinder-comet-shoals' },
  { id: 'copperline-orbital-foundry', name: 'Copperline Orbital Foundry', source: require('./assets/bridge-vistas/copperline-orbital-foundry.jpg'), ambience: 'copperline-orbital-foundry' },
  { id: 'blue-ringworld', name: 'Blue Ringworld', source: require('./assets/bridge-vistas/blue-ringworld-vista.jpg'), ambience: 'blue-meridian' },
  { id: 'astral-nebula', name: 'Astral Nebula', source: require('./assets/picture-events/astral-nebula.jpg'), ambience: 'nebula-clouds' },
  { id: 'ringworld-horizon', name: 'Ringworld Horizon', source: require('./assets/picture-events/ringworld-horizon.jpg'), ambience: 'nacre-ice-giant' },
  { id: 'stellar-clouds', name: 'Stellar Clouds', source: require('./assets/picture-events/stellar-clouds.jpg'), ambience: 'nebula-clouds' },
  { id: 'pelagic-megacity', name: 'Pelagic Megacity', source: require('./assets/bridge-vistas/pelagic-megacity.jpg'), ambience: 'pelagic-megacity' },
  { id: 'emberline-shipyard', name: 'Emberline Shipyard', source: require('./assets/bridge-vistas/emberline-shipyard.jpg'), ambience: 'emberline-shipyard' },
  { id: 'nacre-ice-giant', name: 'Nacre Ice Giant', source: require('./assets/bridge-vistas/nacre-ice-giant.jpg'), ambience: 'nacre-ice-giant' },
  { id: 'eventide-binary-eclipse', name: 'Eventide Binary Eclipse', source: require('./assets/bridge-vistas/eventide-binary-eclipse.jpg'), ambience: 'eventide-eclipse' },
  { id: 'glass-desert-dawn', name: 'Glass Desert at Dawn', source: require('./assets/bridge-vistas/glass-desert-dawn.png'), ambience: 'glass-desert' },
  { id: 'pilgrim-beacons', name: 'The Pilgrim Beacons', source: require('./assets/bridge-vistas/pilgrim-beacons.png'), ambience: 'pilgrim-beacons' },
  { id: 'aurora-reef', name: 'The Aurora Reef', source: require('./assets/bridge-vistas/aurora-reef.png'), ambience: 'aurora-reef' },
  { id: 'comet-caravan', name: 'Comet Caravan', source: require('./assets/bridge-vistas/comet-caravan.png'), ambience: 'comet-caravan' },
  { id: 'blue-meridian', name: 'Blue Meridian', source: require('./assets/bridge-vistas/blue-meridian.png'), ambience: 'blue-meridian' },
  { id: 'vesper-horizon', name: 'Vesper Horizon', source: require('./assets/bridge-vistas/vesper-horizon.png'), ambience: 'vesper-horizon' },
  { id: 'blueworld-patrol', name: 'Blueworld Patrol', source: require('./assets/bridge-vistas/blueworld-patrol.png'), ambience: 'blueworld-patrol' },
  { id: 'dawnward-escort', name: 'Dawnward Escort', source: require('./assets/bridge-vistas/dawnward-escort.png'), ambience: 'dawnward-escort' },
  { id: 'emberfall-frontier', name: 'Emberfall Frontier', source: require('./assets/bridge-vistas/emberfall-frontier.png'), ambience: 'emberfall-frontier' },
  { id: 'leviathan-orbit', name: 'Leviathan Orbit', source: require('./assets/bridge-vistas/leviathan-orbit.png'), ambience: 'leviathan-orbit' },
  { id: 'krea-space-scape', name: 'Krea Space Scape', source: { type: 'video', asset: require('./assets/bridge-vistas/krea-space-scape.mp4') } },
  { id: 'violet-rimlands', name: 'Violet Rimlands', source: require('./assets/bridge-vistas/violet-rimlands.jpg'), ambience: 'none' },
  { id: 'quiet-supernova', name: 'Quiet Supernova', source: require('./assets/bridge-vistas/quiet-supernova.jpg'), ambience: 'none' },
  { id: 'pilgrim-ring-station', name: 'Pilgrim Ring Station', source: require('./assets/bridge-vistas/pilgrim-ring-station.jpg'), ambience: 'none' },
  { id: 'umbral-shardfield', name: 'Umbral Shardfield', source: require('./assets/bridge-vistas/umbral-shardfield.jpg'), ambience: 'none' },
  { id: 'roseglass-observation-deck', name: 'Roseglass Observation Deck', source: require('./assets/bridge-vistas/roseglass-observation-deck.jpg'), ambience: 'none' },
  { id: 'midnight-anchorage', name: 'Midnight Anchorage', source: require('./assets/bridge-vistas/midnight-anchorage.jpg'), ambience: 'none' },
  { id: 'somber-nebula', name: 'Somber Nebula', source: require('./assets/bridge-vistas/somber-nebula.jpg'), ambience: 'none' },
  { id: 'amber-ringworld', name: 'Amber Ringworld', source: require('./assets/bridge-vistas/amber-ringworld.png'), ambience: 'none', pictureEventUnlock: true },
  { id: 'violet-giant', name: 'Violet Giant', source: require('./assets/bridge-vistas/violet-giant.png'), ambience: 'none', pictureEventUnlock: true },
  { id: 'emerald-ocean', name: 'Emerald Ocean', source: require('./assets/bridge-vistas/emerald-ocean.png'), ambience: 'none', pictureEventUnlock: true },
  { id: 'ancient-megastructure', name: 'Ancient Megastructure', source: require('./assets/bridge-vistas/ancient-megastructure.png'), ambience: 'none', pictureEventUnlock: true },
  { id: 'eclipse-over-fire', name: 'Eclipse over Fire', source: require('./assets/bridge-vistas/eclipse-over-fire.png'), ambience: 'none', pictureEventUnlock: true },
  { id: 'star-nursery', name: 'Star Nursery', source: require('./assets/bridge-vistas/star-nursery.png'), ambience: 'none', pictureEventUnlock: true },
  { id: 'broken-halo', name: 'The Broken Halo', source: require('./assets/bridge-vistas/broken-halo.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'wandering-world', name: 'The Wandering World', source: require('./assets/bridge-vistas/wandering-world.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'glass-sea', name: 'The Glass Sea', source: require('./assets/bridge-vistas/glass-sea.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'red-dwarf-shadow', name: 'The Red Dwarf’s Shadow', source: require('./assets/bridge-vistas/red-dwarf-shadow.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'great-storm', name: 'The Great Storm', source: require('./assets/bridge-vistas/great-storm.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'pilgrim-fleet', name: 'The Pilgrim Fleet', source: require('./assets/bridge-vistas/pilgrim-fleet.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'gravity-well', name: 'The Gravity Well', source: require('./assets/bridge-vistas/gravity-well.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'hanging-gardens', name: 'The Hanging Gardens', source: require('./assets/bridge-vistas/hanging-gardens.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'silent-wreck', name: 'The Silent Wreck', source: require('./assets/bridge-vistas/silent-wreck.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'far-lanterns', name: 'The Far Lanterns', source: require('./assets/bridge-vistas/far-lanterns.jpg'), ambience: 'none', pictureEventUnlock: true },
  // 60 new still-scene Picture Event rewards. Shared renderer supplies the
  // per-scene randomized drift while ambience remains image-only.
  { id: 'glassstorm-expanse', name: 'Glassstorm Expanse', source: require('./assets/bridge-vistas/glassstorm-expanse.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'pilgrims-ladder', name: "Pilgrim's Ladder", source: require('./assets/bridge-vistas/pilgrims-ladder.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'sunwell-containment-array', name: 'Sunwell Containment Array', source: require('./assets/bridge-vistas/sunwell-containment-array.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'wandering-ark', name: 'Wandering Ark', source: require('./assets/bridge-vistas/wandering-ark.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'rift-tide-moon', name: 'Rift-Tide Moon', source: require('./assets/bridge-vistas/rift-tide-moon.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'saffron-expanse', name: 'Saffron Expanse', source: require('./assets/bridge-vistas/saffron-expanse.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'listening-array', name: 'Listening Array', source: require('./assets/bridge-vistas/listening-array.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'blackglass-shore', name: 'Blackglass Shore', source: require('./assets/bridge-vistas/blackglass-shore.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'archive-vault', name: 'Archive Vault', source: require('./assets/bridge-vistas/archive-vault.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'lantern-migration', name: 'Lantern Migration', source: require('./assets/bridge-vistas/lantern-migration.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'tidal-foundry', name: 'Tidal Foundry', source: require('./assets/bridge-vistas/tidal-foundry.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'cobalt-thunderhead', name: 'Cobalt Thunderhead', source: require('./assets/bridge-vistas/cobalt-thunderhead.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'quiet-crossing', name: 'Quiet Crossing', source: require('./assets/bridge-vistas/quiet-crossing.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'iron-orchard', name: 'Iron Orchard', source: require('./assets/bridge-vistas/iron-orchard.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'crown-of-embers', name: 'Crown of Embers', source: require('./assets/bridge-vistas/crown-of-embers.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'deepwater-window', name: 'Deepwater Window', source: require('./assets/bridge-vistas/deepwater-window.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'clockwork-eclipse', name: 'Clockwork Eclipse', source: require('./assets/bridge-vistas/clockwork-eclipse.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'pale-signal', name: 'Pale Signal', source: require('./assets/bridge-vistas/pale-signal.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'last-greenhouse', name: 'Last Greenhouse', source: require('./assets/bridge-vistas/last-greenhouse.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'cartographers-wake', name: "Cartographer's Wake", source: require('./assets/bridge-vistas/cartographers-wake.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'pulsar-lighthouse', name: 'Pulsar Lighthouse', source: require('./assets/bridge-vistas/pulsar-lighthouse.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'ribbonworld-canyon', name: 'Ribbonworld Canyon', source: require('./assets/bridge-vistas/ribbonworld-canyon.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'long-migration', name: 'Long Migration', source: require('./assets/bridge-vistas/long-migration.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'tidebreak-moon', name: 'Tidebreak Moon', source: require('./assets/bridge-vistas/tidebreak-moon.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'nightglass-metropolis', name: 'Nightglass Metropolis', source: require('./assets/bridge-vistas/nightglass-metropolis.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'solar-sail-regatta', name: 'Solar Sail Regatta', source: require('./assets/bridge-vistas/solar-sail-regatta.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'rings-at-the-edge', name: 'Rings at the Edge', source: require('./assets/bridge-vistas/rings-at-the-edge.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'under-the-blue-giant', name: 'Under the Blue Giant', source: require('./assets/bridge-vistas/under-the-blue-giant.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'ashfall-basin', name: 'Ashfall Basin', source: require('./assets/bridge-vistas/ashfall-basin.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'sleeper-shipyard', name: 'Sleeper Shipyard', source: require('./assets/bridge-vistas/sleeper-shipyard.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'satellite-crown', name: 'Satellite Crown', source: require('./assets/bridge-vistas/satellite-crown.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'silver-mercury-sea', name: 'Silver Mercury Sea', source: require('./assets/bridge-vistas/silver-mercury-sea.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'ion-veil', name: 'Ion Veil', source: require('./assets/bridge-vistas/ion-veil.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'orchard-of-wrecks', name: 'Orchard of Wrecks', source: require('./assets/bridge-vistas/orchard-of-wrecks.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'glassback-range', name: 'Glassback Range', source: require('./assets/bridge-vistas/glassback-range.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'red-silence', name: 'Red Silence', source: require('./assets/bridge-vistas/red-silence.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'duskline-causeway', name: 'Duskline Causeway', source: require('./assets/bridge-vistas/duskline-causeway.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'black-current', name: 'Black Current', source: require('./assets/bridge-vistas/black-current.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'burnished-exosphere', name: 'Burnished Exosphere', source: require('./assets/bridge-vistas/burnished-exosphere.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'dust-choir', name: 'Dust Choir', source: require('./assets/bridge-vistas/dust-choir.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'long-shadow-convoy', name: 'Long Shadow Convoy', source: require('./assets/bridge-vistas/long-shadow-convoy.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'vitrified-forest', name: 'Vitrified Forest', source: require('./assets/bridge-vistas/vitrified-forest.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'magnetar-veil', name: 'Magnetar Veil', source: require('./assets/bridge-vistas/magnetar-veil.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'first-light-at-varda', name: 'First Light at Varda', source: require('./assets/bridge-vistas/first-light-at-varda.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'hollow-comet', name: 'Hollow Comet', source: require('./assets/bridge-vistas/hollow-comet.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'resonance-spires', name: 'Resonance Spires', source: require('./assets/bridge-vistas/resonance-spires.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'flooded-crater', name: 'Flooded Crater', source: require('./assets/bridge-vistas/flooded-crater.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'salt-of-the-void', name: 'Salt of the Void', source: require('./assets/bridge-vistas/salt-of-the-void.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'violet-rain', name: 'Violet Rain', source: require('./assets/bridge-vistas/violet-rain.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'cloud-harbor', name: 'Cloud Harbor', source: require('./assets/bridge-vistas/cloud-harbor.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'unmoored-moon', name: 'Unmoored Moon', source: require('./assets/bridge-vistas/unmoored-moon.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'choir-of-antennas', name: 'Choir of Antennas', source: require('./assets/bridge-vistas/choir-of-antennas.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'glass-rain-night-world', name: 'Glass Rain on a Night World', source: require('./assets/bridge-vistas/glass-rain-night-world.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'magnetotail-comet', name: 'Magnetotail Comet', source: require('./assets/bridge-vistas/magnetotail-comet.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'hollow-sea', name: 'The Hollow Sea', source: require('./assets/bridge-vistas/hollow-sea.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'half-lit-ring-habitat', name: 'Half-lit Ring Habitat', source: require('./assets/bridge-vistas/half-lit-ring-habitat.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'gravitational-lens', name: 'Gravitational Lens', source: require('./assets/bridge-vistas/gravitational-lens.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'eclipsed-pulsar', name: 'Eclipsed Pulsar', source: require('./assets/bridge-vistas/eclipsed-pulsar.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'seed-vault-convoy', name: 'Seed Vault Convoy', source: require('./assets/bridge-vistas/seed-vault-convoy.jpg'), ambience: 'none', pictureEventUnlock: true },
  { id: 'terminal-ocean', name: 'The Terminal Ocean', source: require('./assets/bridge-vistas/terminal-ocean.jpg'), ambience: 'none', pictureEventUnlock: true },
];
